# Layout for Microsoft Xbox controllers
#
#         (LB)                                 (RB)
#         (LT)                                 (RT)
#      _=====_                              _=====_
#     /       \                            /       \
#    /         ----------------------------         \
#   /   ___                                   (Y)    \
#  /   / L \                                          \
# /    \___/                              (X)     (B)  \
# |                   #         =                      |
# |                                           (A)      |
# |             _                    ___               |
# |          __| |__                / R \              |
# |         |__   __|               \___/              |
# |            |_|                                     |
# |             /------------------------\             |
# |            /                          \            |
# |           /                            \           |
# \          /                              \          /
#  \________/                                \________/
#
# BUTTON         Value
#   LB             6
#   RB             7
#   A              0
#   B              1
#   X              3
#   Y              4
# L (click)       13
# R (click)       14
# menu (=)        11
# window (#)      unmapped

#
#    AXIS        Value
# Left Horiz.      0
# Left Vert.       1
# Right Horiz.     2
# Right Vert.      3
#    LT            5
#    RT            4  # yes, really, RT is 4, not 5
# D-pad Horiz.     6
# D-pad Vert.      7

teleop_twist_joy_node:
  ros__parameters:
    publish_stamped_twist: True
    use_sim_time: False
    axis_linear.x: 1
    scale_linear.x: 0.4
    scale_linear_turbo.x: 1.0
    axis_angular.yaw: 0
    scale_angular.yaw: 0.6
    scale_angular_turbo.yaw: 1.2
    enable_button: 6
    enable_turbo_button: 7
joy_node:
  ros__parameters:
    use_sim_time: False
    deadzone: 0.1
    autorepeat_rate: 20.0
    dev: /dev/input/xbox
bt_cutoff_node:
  ros__parameters:
    quality_cutoff: 20
